name: KORONE-BTN-CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run Install
      run: npm install
    - name: Run Build
      run: npm run build

    - name: Deploy to Coding.net
      working-directory: dist
      run: |
        git init
        git config user.name "GitHub Actions Bot"
        git config user.email "copperion@outlook.com"
        git add --all .
        git commit -m "Deploy from GitHub: $GITHUB_SHA"
        git push --force --quiet "https://CcoRMLeNqi:${{ secrets.CODING_TOKEN }}@e.coding.net/copperion/okayu-button.git" master:master
